=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.30-SNAPSHOT

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'date'

module Radarbox
  class GeoSearchQuery
    attr_accessor :min_latitude

    attr_accessor :max_latitude

    attr_accessor :min_longitude

    attr_accessor :max_longitude

    attr_accessor :below_altitude

    attr_accessor :above_altitude

    attr_accessor :include_flight_paths

    attr_accessor :registrations

    attr_accessor :mode_s_hex_codes

    attr_accessor :from_date

    attr_accessor :to_date

    attr_accessor :airlines

    attr_accessor :aircraft_types

    attr_accessor :aircraft_classes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'min_latitude' => :'minLatitude',
        :'max_latitude' => :'maxLatitude',
        :'min_longitude' => :'minLongitude',
        :'max_longitude' => :'maxLongitude',
        :'below_altitude' => :'belowAltitude',
        :'above_altitude' => :'aboveAltitude',
        :'include_flight_paths' => :'includeFlightPaths',
        :'registrations' => :'registrations',
        :'mode_s_hex_codes' => :'modeSHexCodes',
        :'from_date' => :'fromDate',
        :'to_date' => :'toDate',
        :'airlines' => :'airlines',
        :'aircraft_types' => :'aircraftTypes',
        :'aircraft_classes' => :'aircraftClasses'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'min_latitude' => :'Object',
        :'max_latitude' => :'Object',
        :'min_longitude' => :'Object',
        :'max_longitude' => :'Object',
        :'below_altitude' => :'Object',
        :'above_altitude' => :'Object',
        :'include_flight_paths' => :'Object',
        :'registrations' => :'Object',
        :'mode_s_hex_codes' => :'Object',
        :'from_date' => :'Object',
        :'to_date' => :'Object',
        :'airlines' => :'Object',
        :'aircraft_types' => :'Object',
        :'aircraft_classes' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Radarbox::GeoSearchQuery` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Radarbox::GeoSearchQuery`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'min_latitude')
        self.min_latitude = attributes[:'min_latitude']
      end

      if attributes.key?(:'max_latitude')
        self.max_latitude = attributes[:'max_latitude']
      end

      if attributes.key?(:'min_longitude')
        self.min_longitude = attributes[:'min_longitude']
      end

      if attributes.key?(:'max_longitude')
        self.max_longitude = attributes[:'max_longitude']
      end

      if attributes.key?(:'below_altitude')
        self.below_altitude = attributes[:'below_altitude']
      end

      if attributes.key?(:'above_altitude')
        self.above_altitude = attributes[:'above_altitude']
      end

      if attributes.key?(:'include_flight_paths')
        self.include_flight_paths = attributes[:'include_flight_paths']
      end

      if attributes.key?(:'registrations')
        if (value = attributes[:'registrations']).is_a?(Array)
          self.registrations = value
        end
      end

      if attributes.key?(:'mode_s_hex_codes')
        if (value = attributes[:'mode_s_hex_codes']).is_a?(Array)
          self.mode_s_hex_codes = value
        end
      end

      if attributes.key?(:'from_date')
        self.from_date = attributes[:'from_date']
      end

      if attributes.key?(:'to_date')
        self.to_date = attributes[:'to_date']
      end

      if attributes.key?(:'airlines')
        if (value = attributes[:'airlines']).is_a?(Array)
          self.airlines = value
        end
      end

      if attributes.key?(:'aircraft_types')
        if (value = attributes[:'aircraft_types']).is_a?(Array)
          self.aircraft_types = value
        end
      end

      if attributes.key?(:'aircraft_classes')
        if (value = attributes[:'aircraft_classes']).is_a?(Array)
          self.aircraft_classes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @min_latitude.nil?
        invalid_properties.push('invalid value for "min_latitude", min_latitude cannot be nil.')
      end

      if @max_latitude.nil?
        invalid_properties.push('invalid value for "max_latitude", max_latitude cannot be nil.')
      end

      if @min_longitude.nil?
        invalid_properties.push('invalid value for "min_longitude", min_longitude cannot be nil.')
      end

      if @max_longitude.nil?
        invalid_properties.push('invalid value for "max_longitude", max_longitude cannot be nil.')
      end

      if @from_date.nil?
        invalid_properties.push('invalid value for "from_date", from_date cannot be nil.')
      end

      if @to_date.nil?
        invalid_properties.push('invalid value for "to_date", to_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @min_latitude.nil?
      return false if @max_latitude.nil?
      return false if @min_longitude.nil?
      return false if @max_longitude.nil?
      return false if @from_date.nil?
      return false if @to_date.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          min_latitude == o.min_latitude &&
          max_latitude == o.max_latitude &&
          min_longitude == o.min_longitude &&
          max_longitude == o.max_longitude &&
          below_altitude == o.below_altitude &&
          above_altitude == o.above_altitude &&
          include_flight_paths == o.include_flight_paths &&
          registrations == o.registrations &&
          mode_s_hex_codes == o.mode_s_hex_codes &&
          from_date == o.from_date &&
          to_date == o.to_date &&
          airlines == o.airlines &&
          aircraft_types == o.aircraft_types &&
          aircraft_classes == o.aircraft_classes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [min_latitude, max_latitude, min_longitude, max_longitude, below_altitude, above_altitude, include_flight_paths, registrations, mode_s_hex_codes, from_date, to_date, airlines, aircraft_types, aircraft_classes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        Radarbox.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
