=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.31

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for Radarbox::AircraftApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AircraftApi' do
  before do
    # run before each test
    @instance = Radarbox::AircraftApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AircraftApi' do
    it 'should create an instance of AircraftApi' do
      expect(@instance).to be_instance_of(Radarbox::AircraftApi)
    end
  end

  # unit tests for get_aircraft
  # Aircraft by id
  # Get aircraft details by id (Mode-S hex code or tail number
  # @param [Hash] opts the optional parameters
  # @option opts [String] :mode_s Mode-S code
  # @option opts [String] :registration Registration
  # @return [GetAircraftResponse]
  describe 'get_aircraft test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
