=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.31

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for Radarbox::AirportsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AirportsApi' do
  before do
    # run before each test
    @instance = Radarbox::AirportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AirportsApi' do
    it 'should create an instance of AirportsApi' do
      expect(@instance).to be_instance_of(Radarbox::AirportsApi)
    end
  end

  # unit tests for get_airport
  # Airport by code
  # Get airport details by code
  # @param icao_code ICAO code
  # @param [Hash] opts the optional parameters
  # @return [GetAirportResponse]
  describe 'get_airport test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_metar
  # Get METAR by airport
  # Get airport Metar by code
  # @param icao_code ICAO code
  # @param [Hash] opts the optional parameters
  # @return [GetMetarResponse]
  describe 'get_metar test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_notams
  # Get NOTAMS by airport
  # Get airport NOTAMS by code
  # @param icao_code ICAO code
  # @param [Hash] opts the optional parameters
  # @return [GetNotamsResponse]
  describe 'get_notams test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_taf
  # Get TAF by airport
  # Get airport TAF by code
  # @param icao_code ICAO code
  # @param [Hash] opts the optional parameters
  # @return [GetTafResponse]
  describe 'get_taf test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
