=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.1.14

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for Radarbox::AirspaceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AirspaceApi' do
  before do
    # run before each test
    @instance = Radarbox::AirspaceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AirspaceApi' do
    it 'should create an instance of AirspaceApi' do
      expect(@instance).to be_instance_of(Radarbox::AirspaceApi)
    end
  end

  # unit tests for get_nat_tracks
  # NAT (North Atlantic Tracks)
  # The North Atlantic Tracks are high altitude routes across the atlantic between Western Europe and North America. The tracks are updated daily. Use this endpoint to get the most up-to-date tracks
  # @param [Hash] opts the optional parameters
  # @return [GetNatPacTracksResponse]
  describe 'get_nat_tracks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_notams
  # Get NOTAMS by airport
  # NOTAMs (NOtice To AirMen) are a way of local aviation authorities alerting pilots of potential hazards. Use this endpoint if you want to see the alerts that are relevant for a specific airport.
  # @param icao_code ICAO code
  # @param [Hash] opts the optional parameters
  # @return [GetNotamsResponse]
  describe 'get_notams test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pac_tracks
  # PAC (Pacific Organized Track System - PACOTS) 
  # Pacific Organized Track System describes the set of routes across the Pacific between Hawaii or North America and Japan/South-east Asia - updated on a daily basis. Use this endpoint to get the most up-to-date information.
  # @param [Hash] opts the optional parameters
  # @return [GetNatPacTracksResponse]
  describe 'get_pac_tracks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
