=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.1.14

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for Radarbox::StatisticsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatisticsApi' do
  before do
    # run before each test
    @instance = Radarbox::StatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatisticsApi' do
    it 'should create an instance of StatisticsApi' do
      expect(@instance).to be_instance_of(Radarbox::StatisticsApi)
    end
  end

  # unit tests for get_airlines_statistics
  # Statistics for major airlines
  # Get statistics for major airlines
  # @param [Hash] opts the optional parameters
  # @return [AirlineStatisticsResponse]
  describe 'get_airlines_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_bus_jet_models_statistics_internal
  # Statistics for business jet models
  # Get statistics for business jet models
  # @param [Hash] opts the optional parameters
  # @return [BusinessJetModelStatisticsResponse]
  describe 'get_bus_jet_models_statistics_internal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_bus_jet_operator_statistics_internal
  # Statistics for business jet operators
  # Get statistics for business jet operators
  # @param [Hash] opts the optional parameters
  # @return [BusinessJetOperatorStatisticsResponse]
  describe 'get_bus_jet_operator_statistics_internal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_business_airport_statistics
  # Statistics for business flights on major airports
  # Get statistics for business flights on major airports
  # @param [Hash] opts the optional parameters
  # @return [AirportsStatisticsResponse]
  describe 'get_business_airport_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_business_flights_statistics
  # Flights statistics (business)
  # Get statistics for all business flights
  # @param [Hash] opts the optional parameters
  # @return [FlightsStatisticsResponse]
  describe 'get_business_flights_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_commercial_airport_statistics
  # Statistics for commercial flights on major airports
  # Get statistics for commercial flights on major airports
  # @param [Hash] opts the optional parameters
  # @return [AirportsStatisticsResponse]
  describe 'get_commercial_airport_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_commercial_flights_statistics
  # Flights statistics (commercial)
  # Get statistics for all commercial flights
  # @param [Hash] opts the optional parameters
  # @return [FlightsStatisticsResponse]
  describe 'get_commercial_flights_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_flights_statistics
  # Statistics for all flights
  # Get statistics for all flights worldwide
  # @param [Hash] opts the optional parameters
  # @return [FlightsStatisticsResponse]
  describe 'get_flights_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_major_airport_statistics
  # Statistics for major airports
  # Get statistics for a specific airport
  # @param [Hash] opts the optional parameters
  # @return [AirportsStatisticsResponse]
  describe 'get_major_airport_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
