=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.1.14

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Radarbox::ApiStatisticAirport
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiStatisticAirport' do
  before do
    # run before each test
    @instance = Radarbox::ApiStatisticAirport.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiStatisticAirport' do
    it 'should create an instance of ApiStatisticAirport' do
      expect(@instance).to be_instance_of(Radarbox::ApiStatisticAirport)
    end
  end
  describe 'test attribute "icao_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "movements"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
