=begin
#RadarBox On Demand API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.1.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

# Common files
require 'radarbox-api/api_client'
require 'radarbox-api/api_error'
require 'radarbox-api/version'
require 'radarbox-api/configuration'

# Models
require 'radarbox-api/models/airline_statistics_response'
require 'radarbox-api/models/airports_statistics_response'
require 'radarbox-api/models/api_aircraft'
require 'radarbox-api/models/api_aircraft_statistic'
require 'radarbox-api/models/api_airline_statistic'
require 'radarbox-api/models/api_airline_statistics'
require 'radarbox-api/models/api_airport'
require 'radarbox-api/models/api_airport_statistic'
require 'radarbox-api/models/api_airport_statistics'
require 'radarbox-api/models/api_business_jet_operator_statistic'
require 'radarbox-api/models/api_business_jet_operator_statistics'
require 'radarbox-api/models/api_datis'
require 'radarbox-api/models/api_flight'
require 'radarbox-api/models/api_flight_route_statistic'
require 'radarbox-api/models/api_flights_statistic'
require 'radarbox-api/models/api_jet_model_statistic'
require 'radarbox-api/models/api_jet_model_statistics'
require 'radarbox-api/models/api_metar'
require 'radarbox-api/models/api_nat_pac_track'
require 'radarbox-api/models/api_notam'
require 'radarbox-api/models/api_notam_translation'
require 'radarbox-api/models/api_runway'
require 'radarbox-api/models/api_runway_in_use'
require 'radarbox-api/models/api_statistic_airport'
require 'radarbox-api/models/api_taf'
require 'radarbox-api/models/api_taf_forecast'
require 'radarbox-api/models/api_taf_sky_condition'
require 'radarbox-api/models/api_track_waypoint'
require 'radarbox-api/models/api_trail'
require 'radarbox-api/models/business_jet_model_statistics_response'
require 'radarbox-api/models/business_jet_operator_statistics_response'
require 'radarbox-api/models/coordinates'
require 'radarbox-api/models/flights_query'
require 'radarbox-api/models/flights_response'
require 'radarbox-api/models/flights_statistics_response'
require 'radarbox-api/models/geo_search_query'
require 'radarbox-api/models/get_aircraft_response'
require 'radarbox-api/models/get_airport_response'
require 'radarbox-api/models/get_airports_response'
require 'radarbox-api/models/get_datis_response'
require 'radarbox-api/models/get_metar_response'
require 'radarbox-api/models/get_nat_pac_tracks_response'
require 'radarbox-api/models/get_notams_response'
require 'radarbox-api/models/get_taf_response'
require 'radarbox-api/models/rt_aircraft_position_query'
require 'radarbox-api/models/search_aircraft_response'

# APIs
require 'radarbox-api/api/aircraft_api'
require 'radarbox-api/api/airports_api'
require 'radarbox-api/api/flights_api'
require 'radarbox-api/api/statistics_api'

module Radarbox
  class << self
    # Customize default settings for the SDK using block.
    #   Radarbox.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
